// src/phase1_branding.js
// Deterministic Phase 1 branding and component generator.
// Does not call any LLM by default. If you add model connectors and keys,
// this module can be extended to call them (with user consent).

const fs = require('fs');
const path = require('path');

function safeWrite(filePath, contents, options = { force: false }) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  if (fs.existsSync(filePath) && !options.force) {
    // Do not overwrite existing file by default
    return { skipped: true, path: filePath };
  }
  fs.writeFileSync(filePath, contents, 'utf8');
  return { written: true, path: filePath };
}

function inferFromPRD(prdText = '') {
  // Simple heuristics: find keywords to choose a color / tone
  const lower = (prdText || '').toLowerCase();
  const theme = {
    name: 'vibe-app',
    primary: '#0ea5e9', // sky blue default
    accent: '#7c3aed',
    bg: '#ffffff',
    text: '#0f172a',
    fonts: { display: 'Syne, sans-serif', body: 'Inter, sans-serif' },
  };

  if (lower.includes('finance') || lower.includes('invoice') || lower.includes('billing')) {
    theme.primary = '#0f172a'; // deep navy
    theme.accent = '#d4af37'; // gold
    theme.fonts = { display: 'Neue Haas Grotesk, sans-serif', body: 'Inter, sans-serif' };
  } else if (lower.includes('food') || lower.includes('delivery')) {
    theme.primary = '#ea580c'; // warm orange
    theme.accent = '#065f46'; // deep green
    theme.fonts = { display: 'Fraunces, serif', body: 'Cabinet Grotesk, sans-serif' };
  } else if (lower.includes('health') || lower.includes('wellness')) {
    theme.primary = '#4d7c5f'; // sage green
    theme.accent = '#f59e0b';
    theme.fonts = { display: 'Playfair Display, serif', body: 'Lato, sans-serif' };
  }

  // Return theme tokens
  return theme;
}

function makeLogoSVG(appName = 'Vibe') {
  // Simple SVG logo generator (deterministic)
  const initials = (appName || 'V')
    .split(' ')
    .map((s) => s[0])
    .join('')
    .slice(0, 2)
    .toUpperCase();
  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="240" height="64" viewBox="0 0 240 64" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${appName} logo">
  <rect width="240" height="64" rx="12" fill="#ffffff"/>
  <defs>
    <linearGradient id="g1" x1="0" x2="1">
      <stop offset="0%" stop-color="#0ea5e9"/>
      <stop offset="100%" stop-color="#7c3aed"/>
    </linearGradient>
  </defs>
  <circle cx="40" cy="32" r="20" fill="url(#g1)"/>
  <text x="40" y="38" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-weight="700" font-size="20" fill="#fff">${initials}</text>
  <text x="76" y="38" font-family="Inter, sans-serif" font-size="18" fill="#0f172a">${appName}</text>
</svg>`;
  return svg;
}

function makeButtonComponent(theme) {
  // Returns a React component (JSX) string for a styled button.
  const comp = `import React from 'react';

/**
 * Button.jsx — generated by Vibe-assistant Phase 1
 * Theme tokens used: primary=${theme.primary}, accent=${theme.accent}
 * Accessible, simple button for demo / scaffold.
 */

export default function Button({ children, variant = 'primary', onClick, className = '', ...props }) {
  const base = 'inline-flex items-center justify-center font-semibold rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2';
  const variants = {
    primary: 'bg-[${primary}] text-white hover:opacity-95 px-4 py-2',
    outline: 'border border-gray-200 text-[${text}] px-4 py-2 bg-white',
    ghost: 'bg-transparent text-[${primary}] px-3 py-2',
  };
  const cls = [base, variants[variant] || variants.primary, className].join(' ');
  return (
    <button className={cls} onClick={onClick} {...props}>
      {children}
    </button>
  );
}
`.replace(/\$\{primary\}/g, theme.primary).replace(/\$\{text\}/g, theme.text || '#0f172a');
  return comp;
}

function generateBranding({ prd = '', options = {} } = {}) {
  const theme = inferFromPRD(prd);
  const appNameMatch = (prd && prd.split('\n')[0]) || options.appName || theme.name;
  const appName = (appNameMatch || 'Vibe').replace(/^#\s*/, '').trim();

  // Generate assets
  const logoSvg = makeLogoSVG(appName);
  const buttonComponent = makeButtonComponent(theme);

  return { theme: { name: appName, tokens: theme }, logoSvg, buttonComponent };
}

// Optional helper: write default theme file and sample component
function writeOutputs(baseDir = process.cwd(), brandingOutput = {}) {
  const out = [];
  const themePath = path.join(baseDir, 'branding', 'theme.json');
  const logoPath = path.join(baseDir, 'branding', 'logo.svg');
  const btnPath = path.join(baseDir, 'components', 'ui', 'Button.jsx');

  if (brandingOutput.theme) {
    safeWrite(themePath, JSON.stringify(brandingOutput.theme, null, 2));
    out.push(themePath);
  }
  if (brandingOutput.logoSvg) {
    safeWrite(logoPath, brandingOutput.logoSvg);
    out.push(logoPath);
  }
  if (brandingOutput.buttonComponent) {
    safeWrite(btnPath, brandingOutput.buttonComponent);
    out.push(btnPath);
  }

  return out;
}

module.exports = { generateBranding, writeOutputs, inferFromPRD };
